# Take a look at the mayflower/php module docs for more
# information. https://forge.puppetlabs.com/mayflower/php

# Use latest available php version
php::ensure: latest
php::manage_repos: true

# Use fpm?
php::fpm: true
php::dev: true

# Install composer?
php::composer: true
php::pear: true

# Install phpunit?
php::phpunit: true
php::fpm::config:log_level: notice
php::composer::auto_update: true

# These kev/value pairs will be added 
# to your php.ini. 
php::settings:
    Date/date.timezone: America/New_York
    error_reporting: -1
php::cli::settings:
    PHP/memory_limit: 9999M
php::fpm::settings:
    PHP/short_open_tag: 'On'

# Define which extensions to include
# and configure them
php::extensions:
    mysql: {}
    curl: {}
    json: {}
    intl: {}
    gd: {}
